package com.ayang818.honor.datacollection.model;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories_dict.id
     *
     * @mbg.generated Sun Nov 03 15:07:40 GMT+08:00 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories_dict.title
     *
     * @mbg.generated Sun Nov 03 15:07:40 GMT+08:00 2019
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories_dict.id
     *
     * @return the value of categories_dict.id
     *
     * @mbg.generated Sun Nov 03 15:07:40 GMT+08:00 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories_dict.id
     *
     * @param id the value for categories_dict.id
     *
     * @mbg.generated Sun Nov 03 15:07:40 GMT+08:00 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories_dict.title
     *
     * @return the value of categories_dict.title
     *
     * @mbg.generated Sun Nov 03 15:07:40 GMT+08:00 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories_dict.title
     *
     * @param title the value for categories_dict.title
     *
     * @mbg.generated Sun Nov 03 15:07:40 GMT+08:00 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
}