package com.ayang818.honor.datacollection.model;

public class ClosureTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closure_table.ancestor
     *
     * @mbg.generated Tue Oct 29 11:25:16 CST 2019
     */
    private Long ancestor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closure_table.descendant
     *
     * @mbg.generated Tue Oct 29 11:25:16 CST 2019
     */
    private Long descendant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closure_table.distance
     *
     * @mbg.generated Tue Oct 29 11:25:16 CST 2019
     */
    private Long distance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closure_table.ancestor
     *
     * @return the value of closure_table.ancestor
     *
     * @mbg.generated Tue Oct 29 11:25:16 CST 2019
     */
    public Long getAncestor() {
        return ancestor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closure_table.ancestor
     *
     * @param ancestor the value for closure_table.ancestor
     *
     * @mbg.generated Tue Oct 29 11:25:16 CST 2019
     */
    public void setAncestor(Long ancestor) {
        this.ancestor = ancestor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closure_table.descendant
     *
     * @return the value of closure_table.descendant
     *
     * @mbg.generated Tue Oct 29 11:25:16 CST 2019
     */
    public Long getDescendant() {
        return descendant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closure_table.descendant
     *
     * @param descendant the value for closure_table.descendant
     *
     * @mbg.generated Tue Oct 29 11:25:16 CST 2019
     */
    public void setDescendant(Long descendant) {
        this.descendant = descendant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closure_table.distance
     *
     * @return the value of closure_table.distance
     *
     * @mbg.generated Tue Oct 29 11:25:16 CST 2019
     */
    public Long getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closure_table.distance
     *
     * @param distance the value for closure_table.distance
     *
     * @mbg.generated Tue Oct 29 11:25:16 CST 2019
     */
    public void setDistance(Long distance) {
        this.distance = distance;
    }
}