package com.ayang818.honor.datacollection.model;

public class ClosureTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closure_table.ancestor
     *
     * @mbg.generated Mon Oct 28 23:48:18 CST 2019
     */
    private Integer ancestor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closure_table.descendant
     *
     * @mbg.generated Mon Oct 28 23:48:18 CST 2019
     */
    private Integer descendant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closure_table.distance
     *
     * @mbg.generated Mon Oct 28 23:48:18 CST 2019
     */
    private Integer distance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closure_table.ancestor
     *
     * @return the value of closure_table.ancestor
     *
     * @mbg.generated Mon Oct 28 23:48:18 CST 2019
     */
    public Integer getAncestor() {
        return ancestor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closure_table.ancestor
     *
     * @param ancestor the value for closure_table.ancestor
     *
     * @mbg.generated Mon Oct 28 23:48:18 CST 2019
     */
    public void setAncestor(Integer ancestor) {
        this.ancestor = ancestor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closure_table.descendant
     *
     * @return the value of closure_table.descendant
     *
     * @mbg.generated Mon Oct 28 23:48:18 CST 2019
     */
    public Integer getDescendant() {
        return descendant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closure_table.descendant
     *
     * @param descendant the value for closure_table.descendant
     *
     * @mbg.generated Mon Oct 28 23:48:18 CST 2019
     */
    public void setDescendant(Integer descendant) {
        this.descendant = descendant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closure_table.distance
     *
     * @return the value of closure_table.distance
     *
     * @mbg.generated Mon Oct 28 23:48:18 CST 2019
     */
    public Integer getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closure_table.distance
     *
     * @param distance the value for closure_table.distance
     *
     * @mbg.generated Mon Oct 28 23:48:18 CST 2019
     */
    public void setDistance(Integer distance) {
        this.distance = distance;
    }
}