package com.ayang818.honor.datacollection.model;

import java.util.Date;

public class CompetitionHonor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.id
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.competition_type
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    private String competitionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.competition_level
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    private String competitionLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.competition_year
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    private String competitionYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.competition_total_name
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    private String competitionTotalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.team_number
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    private String teamNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.student_name
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.grade
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.school_number
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    private String schoolNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.major
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.college
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    private String college;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.guidance_teacher
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    private String guidanceTeacher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.honor_level
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    private String honorLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.MESSAGE
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.pass
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    private Byte pass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.gmt_create
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.gmt_modified
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.id
     *
     * @return the value of competition_honor.id
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.id
     *
     * @param id the value for competition_honor.id
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.competition_type
     *
     * @return the value of competition_honor.competition_type
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public String getCompetitionType() {
        return competitionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.competition_type
     *
     * @param competitionType the value for competition_honor.competition_type
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public void setCompetitionType(String competitionType) {
        this.competitionType = competitionType == null ? null : competitionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.competition_level
     *
     * @return the value of competition_honor.competition_level
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public String getCompetitionLevel() {
        return competitionLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.competition_level
     *
     * @param competitionLevel the value for competition_honor.competition_level
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public void setCompetitionLevel(String competitionLevel) {
        this.competitionLevel = competitionLevel == null ? null : competitionLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.competition_year
     *
     * @return the value of competition_honor.competition_year
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public String getCompetitionYear() {
        return competitionYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.competition_year
     *
     * @param competitionYear the value for competition_honor.competition_year
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public void setCompetitionYear(String competitionYear) {
        this.competitionYear = competitionYear == null ? null : competitionYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.competition_total_name
     *
     * @return the value of competition_honor.competition_total_name
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public String getCompetitionTotalName() {
        return competitionTotalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.competition_total_name
     *
     * @param competitionTotalName the value for competition_honor.competition_total_name
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public void setCompetitionTotalName(String competitionTotalName) {
        this.competitionTotalName = competitionTotalName == null ? null : competitionTotalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.team_number
     *
     * @return the value of competition_honor.team_number
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public String getTeamNumber() {
        return teamNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.team_number
     *
     * @param teamNumber the value for competition_honor.team_number
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public void setTeamNumber(String teamNumber) {
        this.teamNumber = teamNumber == null ? null : teamNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.student_name
     *
     * @return the value of competition_honor.student_name
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.student_name
     *
     * @param studentName the value for competition_honor.student_name
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.grade
     *
     * @return the value of competition_honor.grade
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.grade
     *
     * @param grade the value for competition_honor.grade
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.school_number
     *
     * @return the value of competition_honor.school_number
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public String getSchoolNumber() {
        return schoolNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.school_number
     *
     * @param schoolNumber the value for competition_honor.school_number
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public void setSchoolNumber(String schoolNumber) {
        this.schoolNumber = schoolNumber == null ? null : schoolNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.major
     *
     * @return the value of competition_honor.major
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.major
     *
     * @param major the value for competition_honor.major
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.college
     *
     * @return the value of competition_honor.college
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.college
     *
     * @param college the value for competition_honor.college
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public void setCollege(String college) {
        this.college = college == null ? null : college.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.guidance_teacher
     *
     * @return the value of competition_honor.guidance_teacher
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public String getGuidanceTeacher() {
        return guidanceTeacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.guidance_teacher
     *
     * @param guidanceTeacher the value for competition_honor.guidance_teacher
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public void setGuidanceTeacher(String guidanceTeacher) {
        this.guidanceTeacher = guidanceTeacher == null ? null : guidanceTeacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.honor_level
     *
     * @return the value of competition_honor.honor_level
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public String getHonorLevel() {
        return honorLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.honor_level
     *
     * @param honorLevel the value for competition_honor.honor_level
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public void setHonorLevel(String honorLevel) {
        this.honorLevel = honorLevel == null ? null : honorLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.MESSAGE
     *
     * @return the value of competition_honor.MESSAGE
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.MESSAGE
     *
     * @param message the value for competition_honor.MESSAGE
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.pass
     *
     * @return the value of competition_honor.pass
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public Byte getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.pass
     *
     * @param pass the value for competition_honor.pass
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public void setPass(Byte pass) {
        this.pass = pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.gmt_create
     *
     * @return the value of competition_honor.gmt_create
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.gmt_create
     *
     * @param gmtCreate the value for competition_honor.gmt_create
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.gmt_modified
     *
     * @return the value of competition_honor.gmt_modified
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.gmt_modified
     *
     * @param gmtModified the value for competition_honor.gmt_modified
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}