package com.ayang818.honor.datacollection.model;

import java.util.Date;

public class CompetionHonor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.id
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.student_name
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.school_number
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    private Integer schoolNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.competition_level
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    private String competitionLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.competition_name
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    private String competitionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.teacher_name
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    private String teacherName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.teacher_id
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    private Long teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.honor_level
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    private String honorLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.prove
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    private String prove;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.pass
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    private Byte pass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.gmt_create
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition_honor.gmt_modified
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.id
     *
     * @return the value of competition_honor.id
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.id
     *
     * @param id the value for competition_honor.id
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.student_name
     *
     * @return the value of competition_honor.student_name
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.student_name
     *
     * @param studentName the value for competition_honor.student_name
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.school_number
     *
     * @return the value of competition_honor.school_number
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    public Integer getSchoolNumber() {
        return schoolNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.school_number
     *
     * @param schoolNumber the value for competition_honor.school_number
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    public void setSchoolNumber(Integer schoolNumber) {
        this.schoolNumber = schoolNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.competition_level
     *
     * @return the value of competition_honor.competition_level
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    public String getCompetitionLevel() {
        return competitionLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.competition_level
     *
     * @param competitionLevel the value for competition_honor.competition_level
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    public void setCompetitionLevel(String competitionLevel) {
        this.competitionLevel = competitionLevel == null ? null : competitionLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.competition_name
     *
     * @return the value of competition_honor.competition_name
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    public String getCompetitionName() {
        return competitionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.competition_name
     *
     * @param competitionName the value for competition_honor.competition_name
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    public void setCompetitionName(String competitionName) {
        this.competitionName = competitionName == null ? null : competitionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.teacher_name
     *
     * @return the value of competition_honor.teacher_name
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.teacher_name
     *
     * @param teacherName the value for competition_honor.teacher_name
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.teacher_id
     *
     * @return the value of competition_honor.teacher_id
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    public Long getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.teacher_id
     *
     * @param teacherId the value for competition_honor.teacher_id
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.honor_level
     *
     * @return the value of competition_honor.honor_level
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    public String getHonorLevel() {
        return honorLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.honor_level
     *
     * @param honorLevel the value for competition_honor.honor_level
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    public void setHonorLevel(String honorLevel) {
        this.honorLevel = honorLevel == null ? null : honorLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.prove
     *
     * @return the value of competition_honor.prove
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    public String getProve() {
        return prove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.prove
     *
     * @param prove the value for competition_honor.prove
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    public void setProve(String prove) {
        this.prove = prove == null ? null : prove.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.pass
     *
     * @return the value of competition_honor.pass
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    public Byte getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.pass
     *
     * @param pass the value for competition_honor.pass
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    public void setPass(Byte pass) {
        this.pass = pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.gmt_create
     *
     * @return the value of competition_honor.gmt_create
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.gmt_create
     *
     * @param gmtCreate the value for competition_honor.gmt_create
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition_honor.gmt_modified
     *
     * @return the value of competition_honor.gmt_modified
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition_honor.gmt_modified
     *
     * @param gmtModified the value for competition_honor.gmt_modified
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}