package com.ayang818.honor.datacollection.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CompetitionHonorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table competition_honor
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table competition_honor
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table competition_honor
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition_honor
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public CompetitionHonorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition_honor
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition_honor
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition_honor
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition_honor
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition_honor
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition_honor
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition_honor
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition_honor
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition_honor
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition_honor
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table competition_honor
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCompetitionTypeIsNull() {
            addCriterion("competition_type is null");
            return (Criteria) this;
        }

        public Criteria andCompetitionTypeIsNotNull() {
            addCriterion("competition_type is not null");
            return (Criteria) this;
        }

        public Criteria andCompetitionTypeEqualTo(String value) {
            addCriterion("competition_type =", value, "COMPETITION_TYPE");
            return (Criteria) this;
        }

        public Criteria andCompetitionTypeNotEqualTo(String value) {
            addCriterion("competition_type <>", value, "COMPETITION_TYPE");
            return (Criteria) this;
        }

        public Criteria andCompetitionTypeGreaterThan(String value) {
            addCriterion("competition_type >", value, "COMPETITION_TYPE");
            return (Criteria) this;
        }

        public Criteria andCompetitionTypeGreaterThanOrEqualTo(String value) {
            addCriterion("competition_type >=", value, "COMPETITION_TYPE");
            return (Criteria) this;
        }

        public Criteria andCompetitionTypeLessThan(String value) {
            addCriterion("competition_type <", value, "COMPETITION_TYPE");
            return (Criteria) this;
        }

        public Criteria andCompetitionTypeLessThanOrEqualTo(String value) {
            addCriterion("competition_type <=", value, "COMPETITION_TYPE");
            return (Criteria) this;
        }

        public Criteria andCompetitionTypeLike(String value) {
            addCriterion("competition_type like", value, "COMPETITION_TYPE");
            return (Criteria) this;
        }

        public Criteria andCompetitionTypeNotLike(String value) {
            addCriterion("competition_type not like", value, "COMPETITION_TYPE");
            return (Criteria) this;
        }

        public Criteria andCompetitionTypeIn(List<String> values) {
            addCriterion("competition_type in", values, "COMPETITION_TYPE");
            return (Criteria) this;
        }

        public Criteria andCompetitionTypeNotIn(List<String> values) {
            addCriterion("competition_type not in", values, "COMPETITION_TYPE");
            return (Criteria) this;
        }

        public Criteria andCompetitionTypeBetween(String value1, String value2) {
            addCriterion("competition_type between", value1, value2, "COMPETITION_TYPE");
            return (Criteria) this;
        }

        public Criteria andCompetitionTypeNotBetween(String value1, String value2) {
            addCriterion("competition_type not between", value1, value2, "COMPETITION_TYPE");
            return (Criteria) this;
        }

        public Criteria andCompetitionLevelIsNull() {
            addCriterion("competition_level is null");
            return (Criteria) this;
        }

        public Criteria andCompetitionLevelIsNotNull() {
            addCriterion("competition_level is not null");
            return (Criteria) this;
        }

        public Criteria andCompetitionLevelEqualTo(String value) {
            addCriterion("competition_level =", value, "COMPETITION_LEVEL");
            return (Criteria) this;
        }

        public Criteria andCompetitionLevelNotEqualTo(String value) {
            addCriterion("competition_level <>", value, "COMPETITION_LEVEL");
            return (Criteria) this;
        }

        public Criteria andCompetitionLevelGreaterThan(String value) {
            addCriterion("competition_level >", value, "COMPETITION_LEVEL");
            return (Criteria) this;
        }

        public Criteria andCompetitionLevelGreaterThanOrEqualTo(String value) {
            addCriterion("competition_level >=", value, "COMPETITION_LEVEL");
            return (Criteria) this;
        }

        public Criteria andCompetitionLevelLessThan(String value) {
            addCriterion("competition_level <", value, "COMPETITION_LEVEL");
            return (Criteria) this;
        }

        public Criteria andCompetitionLevelLessThanOrEqualTo(String value) {
            addCriterion("competition_level <=", value, "COMPETITION_LEVEL");
            return (Criteria) this;
        }

        public Criteria andCompetitionLevelLike(String value) {
            addCriterion("competition_level like", value, "COMPETITION_LEVEL");
            return (Criteria) this;
        }

        public Criteria andCompetitionLevelNotLike(String value) {
            addCriterion("competition_level not like", value, "COMPETITION_LEVEL");
            return (Criteria) this;
        }

        public Criteria andCompetitionLevelIn(List<String> values) {
            addCriterion("competition_level in", values, "COMPETITION_LEVEL");
            return (Criteria) this;
        }

        public Criteria andCompetitionLevelNotIn(List<String> values) {
            addCriterion("competition_level not in", values, "COMPETITION_LEVEL");
            return (Criteria) this;
        }

        public Criteria andCompetitionLevelBetween(String value1, String value2) {
            addCriterion("competition_level between", value1, value2, "COMPETITION_LEVEL");
            return (Criteria) this;
        }

        public Criteria andCompetitionLevelNotBetween(String value1, String value2) {
            addCriterion("competition_level not between", value1, value2, "COMPETITION_LEVEL");
            return (Criteria) this;
        }

        public Criteria andCompetitionYearIsNull() {
            addCriterion("competition_year is null");
            return (Criteria) this;
        }

        public Criteria andCompetitionYearIsNotNull() {
            addCriterion("competition_year is not null");
            return (Criteria) this;
        }

        public Criteria andCompetitionYearEqualTo(String value) {
            addCriterion("competition_year =", value, "COMPETITION_YEAR");
            return (Criteria) this;
        }

        public Criteria andCompetitionYearNotEqualTo(String value) {
            addCriterion("competition_year <>", value, "COMPETITION_YEAR");
            return (Criteria) this;
        }

        public Criteria andCompetitionYearGreaterThan(String value) {
            addCriterion("competition_year >", value, "COMPETITION_YEAR");
            return (Criteria) this;
        }

        public Criteria andCompetitionYearGreaterThanOrEqualTo(String value) {
            addCriterion("competition_year >=", value, "COMPETITION_YEAR");
            return (Criteria) this;
        }

        public Criteria andCompetitionYearLessThan(String value) {
            addCriterion("competition_year <", value, "COMPETITION_YEAR");
            return (Criteria) this;
        }

        public Criteria andCompetitionYearLessThanOrEqualTo(String value) {
            addCriterion("competition_year <=", value, "COMPETITION_YEAR");
            return (Criteria) this;
        }

        public Criteria andCompetitionYearLike(String value) {
            addCriterion("competition_year like", value, "COMPETITION_YEAR");
            return (Criteria) this;
        }

        public Criteria andCompetitionYearNotLike(String value) {
            addCriterion("competition_year not like", value, "COMPETITION_YEAR");
            return (Criteria) this;
        }

        public Criteria andCompetitionYearIn(List<String> values) {
            addCriterion("competition_year in", values, "COMPETITION_YEAR");
            return (Criteria) this;
        }

        public Criteria andCompetitionYearNotIn(List<String> values) {
            addCriterion("competition_year not in", values, "COMPETITION_YEAR");
            return (Criteria) this;
        }

        public Criteria andCompetitionYearBetween(String value1, String value2) {
            addCriterion("competition_year between", value1, value2, "COMPETITION_YEAR");
            return (Criteria) this;
        }

        public Criteria andCompetitionYearNotBetween(String value1, String value2) {
            addCriterion("competition_year not between", value1, value2, "COMPETITION_YEAR");
            return (Criteria) this;
        }

        public Criteria andCompetitionTotalNameIsNull() {
            addCriterion("competition_total_name is null");
            return (Criteria) this;
        }

        public Criteria andCompetitionTotalNameIsNotNull() {
            addCriterion("competition_total_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompetitionTotalNameEqualTo(String value) {
            addCriterion("competition_total_name =", value, "COMPETITION_TOTAL_NAME");
            return (Criteria) this;
        }

        public Criteria andCompetitionTotalNameNotEqualTo(String value) {
            addCriterion("competition_total_name <>", value, "COMPETITION_TOTAL_NAME");
            return (Criteria) this;
        }

        public Criteria andCompetitionTotalNameGreaterThan(String value) {
            addCriterion("competition_total_name >", value, "COMPETITION_TOTAL_NAME");
            return (Criteria) this;
        }

        public Criteria andCompetitionTotalNameGreaterThanOrEqualTo(String value) {
            addCriterion("competition_total_name >=", value, "COMPETITION_TOTAL_NAME");
            return (Criteria) this;
        }

        public Criteria andCompetitionTotalNameLessThan(String value) {
            addCriterion("competition_total_name <", value, "COMPETITION_TOTAL_NAME");
            return (Criteria) this;
        }

        public Criteria andCompetitionTotalNameLessThanOrEqualTo(String value) {
            addCriterion("competition_total_name <=", value, "COMPETITION_TOTAL_NAME");
            return (Criteria) this;
        }

        public Criteria andCompetitionTotalNameLike(String value) {
            addCriterion("competition_total_name like", value, "COMPETITION_TOTAL_NAME");
            return (Criteria) this;
        }

        public Criteria andCompetitionTotalNameNotLike(String value) {
            addCriterion("competition_total_name not like", value, "COMPETITION_TOTAL_NAME");
            return (Criteria) this;
        }

        public Criteria andCompetitionTotalNameIn(List<String> values) {
            addCriterion("competition_total_name in", values, "COMPETITION_TOTAL_NAME");
            return (Criteria) this;
        }

        public Criteria andCompetitionTotalNameNotIn(List<String> values) {
            addCriterion("competition_total_name not in", values, "COMPETITION_TOTAL_NAME");
            return (Criteria) this;
        }

        public Criteria andCompetitionTotalNameBetween(String value1, String value2) {
            addCriterion("competition_total_name between", value1, value2, "COMPETITION_TOTAL_NAME");
            return (Criteria) this;
        }

        public Criteria andCompetitionTotalNameNotBetween(String value1, String value2) {
            addCriterion("competition_total_name not between", value1, value2, "COMPETITION_TOTAL_NAME");
            return (Criteria) this;
        }

        public Criteria andTeamNumberIsNull() {
            addCriterion("team_number is null");
            return (Criteria) this;
        }

        public Criteria andTeamNumberIsNotNull() {
            addCriterion("team_number is not null");
            return (Criteria) this;
        }

        public Criteria andTeamNumberEqualTo(String value) {
            addCriterion("team_number =", value, "teamNumber");
            return (Criteria) this;
        }

        public Criteria andTeamNumberNotEqualTo(String value) {
            addCriterion("team_number <>", value, "teamNumber");
            return (Criteria) this;
        }

        public Criteria andTeamNumberGreaterThan(String value) {
            addCriterion("team_number >", value, "teamNumber");
            return (Criteria) this;
        }

        public Criteria andTeamNumberGreaterThanOrEqualTo(String value) {
            addCriterion("team_number >=", value, "teamNumber");
            return (Criteria) this;
        }

        public Criteria andTeamNumberLessThan(String value) {
            addCriterion("team_number <", value, "teamNumber");
            return (Criteria) this;
        }

        public Criteria andTeamNumberLessThanOrEqualTo(String value) {
            addCriterion("team_number <=", value, "teamNumber");
            return (Criteria) this;
        }

        public Criteria andTeamNumberLike(String value) {
            addCriterion("team_number like", value, "teamNumber");
            return (Criteria) this;
        }

        public Criteria andTeamNumberNotLike(String value) {
            addCriterion("team_number not like", value, "teamNumber");
            return (Criteria) this;
        }

        public Criteria andTeamNumberIn(List<String> values) {
            addCriterion("team_number in", values, "teamNumber");
            return (Criteria) this;
        }

        public Criteria andTeamNumberNotIn(List<String> values) {
            addCriterion("team_number not in", values, "teamNumber");
            return (Criteria) this;
        }

        public Criteria andTeamNumberBetween(String value1, String value2) {
            addCriterion("team_number between", value1, value2, "teamNumber");
            return (Criteria) this;
        }

        public Criteria andTeamNumberNotBetween(String value1, String value2) {
            addCriterion("team_number not between", value1, value2, "teamNumber");
            return (Criteria) this;
        }

        public Criteria andStudentNameIsNull() {
            addCriterion("student_name is null");
            return (Criteria) this;
        }

        public Criteria andStudentNameIsNotNull() {
            addCriterion("student_name is not null");
            return (Criteria) this;
        }

        public Criteria andStudentNameEqualTo(String value) {
            addCriterion("student_name =", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotEqualTo(String value) {
            addCriterion("student_name <>", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameGreaterThan(String value) {
            addCriterion("student_name >", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameGreaterThanOrEqualTo(String value) {
            addCriterion("student_name >=", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLessThan(String value) {
            addCriterion("student_name <", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLessThanOrEqualTo(String value) {
            addCriterion("student_name <=", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLike(String value) {
            addCriterion("student_name like", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotLike(String value) {
            addCriterion("student_name not like", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameIn(List<String> values) {
            addCriterion("student_name in", values, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotIn(List<String> values) {
            addCriterion("student_name not in", values, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameBetween(String value1, String value2) {
            addCriterion("student_name between", value1, value2, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotBetween(String value1, String value2) {
            addCriterion("student_name not between", value1, value2, "studentName");
            return (Criteria) this;
        }

        public Criteria andGradeIsNull() {
            addCriterion("grade is null");
            return (Criteria) this;
        }

        public Criteria andGradeIsNotNull() {
            addCriterion("grade is not null");
            return (Criteria) this;
        }

        public Criteria andGradeEqualTo(String value) {
            addCriterion("grade =", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotEqualTo(String value) {
            addCriterion("grade <>", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThan(String value) {
            addCriterion("grade >", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThanOrEqualTo(String value) {
            addCriterion("grade >=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThan(String value) {
            addCriterion("grade <", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThanOrEqualTo(String value) {
            addCriterion("grade <=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLike(String value) {
            addCriterion("grade like", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotLike(String value) {
            addCriterion("grade not like", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeIn(List<String> values) {
            addCriterion("grade in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotIn(List<String> values) {
            addCriterion("grade not in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeBetween(String value1, String value2) {
            addCriterion("grade between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotBetween(String value1, String value2) {
            addCriterion("grade not between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andSchoolNumberIsNull() {
            addCriterion("school_number is null");
            return (Criteria) this;
        }

        public Criteria andSchoolNumberIsNotNull() {
            addCriterion("school_number is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolNumberEqualTo(String value) {
            addCriterion("school_number =", value, "schoolNumber");
            return (Criteria) this;
        }

        public Criteria andSchoolNumberNotEqualTo(String value) {
            addCriterion("school_number <>", value, "schoolNumber");
            return (Criteria) this;
        }

        public Criteria andSchoolNumberGreaterThan(String value) {
            addCriterion("school_number >", value, "schoolNumber");
            return (Criteria) this;
        }

        public Criteria andSchoolNumberGreaterThanOrEqualTo(String value) {
            addCriterion("school_number >=", value, "schoolNumber");
            return (Criteria) this;
        }

        public Criteria andSchoolNumberLessThan(String value) {
            addCriterion("school_number <", value, "schoolNumber");
            return (Criteria) this;
        }

        public Criteria andSchoolNumberLessThanOrEqualTo(String value) {
            addCriterion("school_number <=", value, "schoolNumber");
            return (Criteria) this;
        }

        public Criteria andSchoolNumberLike(String value) {
            addCriterion("school_number like", value, "schoolNumber");
            return (Criteria) this;
        }

        public Criteria andSchoolNumberNotLike(String value) {
            addCriterion("school_number not like", value, "schoolNumber");
            return (Criteria) this;
        }

        public Criteria andSchoolNumberIn(List<String> values) {
            addCriterion("school_number in", values, "schoolNumber");
            return (Criteria) this;
        }

        public Criteria andSchoolNumberNotIn(List<String> values) {
            addCriterion("school_number not in", values, "schoolNumber");
            return (Criteria) this;
        }

        public Criteria andSchoolNumberBetween(String value1, String value2) {
            addCriterion("school_number between", value1, value2, "schoolNumber");
            return (Criteria) this;
        }

        public Criteria andSchoolNumberNotBetween(String value1, String value2) {
            addCriterion("school_number not between", value1, value2, "schoolNumber");
            return (Criteria) this;
        }

        public Criteria andMajorIsNull() {
            addCriterion("major is null");
            return (Criteria) this;
        }

        public Criteria andMajorIsNotNull() {
            addCriterion("major is not null");
            return (Criteria) this;
        }

        public Criteria andMajorEqualTo(String value) {
            addCriterion("major =", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorNotEqualTo(String value) {
            addCriterion("major <>", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorGreaterThan(String value) {
            addCriterion("major >", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorGreaterThanOrEqualTo(String value) {
            addCriterion("major >=", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorLessThan(String value) {
            addCriterion("major <", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorLessThanOrEqualTo(String value) {
            addCriterion("major <=", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorLike(String value) {
            addCriterion("major like", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorNotLike(String value) {
            addCriterion("major not like", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorIn(List<String> values) {
            addCriterion("major in", values, "major");
            return (Criteria) this;
        }

        public Criteria andMajorNotIn(List<String> values) {
            addCriterion("major not in", values, "major");
            return (Criteria) this;
        }

        public Criteria andMajorBetween(String value1, String value2) {
            addCriterion("major between", value1, value2, "major");
            return (Criteria) this;
        }

        public Criteria andMajorNotBetween(String value1, String value2) {
            addCriterion("major not between", value1, value2, "major");
            return (Criteria) this;
        }

        public Criteria andCollegeIsNull() {
            addCriterion("college is null");
            return (Criteria) this;
        }

        public Criteria andCollegeIsNotNull() {
            addCriterion("college is not null");
            return (Criteria) this;
        }

        public Criteria andCollegeEqualTo(String value) {
            addCriterion("college =", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeNotEqualTo(String value) {
            addCriterion("college <>", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeGreaterThan(String value) {
            addCriterion("college >", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeGreaterThanOrEqualTo(String value) {
            addCriterion("college >=", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeLessThan(String value) {
            addCriterion("college <", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeLessThanOrEqualTo(String value) {
            addCriterion("college <=", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeLike(String value) {
            addCriterion("college like", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeNotLike(String value) {
            addCriterion("college not like", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeIn(List<String> values) {
            addCriterion("college in", values, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeNotIn(List<String> values) {
            addCriterion("college not in", values, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeBetween(String value1, String value2) {
            addCriterion("college between", value1, value2, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeNotBetween(String value1, String value2) {
            addCriterion("college not between", value1, value2, "college");
            return (Criteria) this;
        }

        public Criteria andGuidanceTeacherIsNull() {
            addCriterion("guidance_teacher is null");
            return (Criteria) this;
        }

        public Criteria andGuidanceTeacherIsNotNull() {
            addCriterion("guidance_teacher is not null");
            return (Criteria) this;
        }

        public Criteria andGuidanceTeacherEqualTo(String value) {
            addCriterion("guidance_teacher =", value, "GUIDANCE_TEACHER");
            return (Criteria) this;
        }

        public Criteria andGuidanceTeacherNotEqualTo(String value) {
            addCriterion("guidance_teacher <>", value, "GUIDANCE_TEACHER");
            return (Criteria) this;
        }

        public Criteria andGuidanceTeacherGreaterThan(String value) {
            addCriterion("guidance_teacher >", value, "GUIDANCE_TEACHER");
            return (Criteria) this;
        }

        public Criteria andGuidanceTeacherGreaterThanOrEqualTo(String value) {
            addCriterion("guidance_teacher >=", value, "GUIDANCE_TEACHER");
            return (Criteria) this;
        }

        public Criteria andGuidanceTeacherLessThan(String value) {
            addCriterion("guidance_teacher <", value, "GUIDANCE_TEACHER");
            return (Criteria) this;
        }

        public Criteria andGuidanceTeacherLessThanOrEqualTo(String value) {
            addCriterion("guidance_teacher <=", value, "GUIDANCE_TEACHER");
            return (Criteria) this;
        }

        public Criteria andGuidanceTeacherLike(String value) {
            addCriterion("guidance_teacher like", value, "GUIDANCE_TEACHER");
            return (Criteria) this;
        }

        public Criteria andGuidanceTeacherNotLike(String value) {
            addCriterion("guidance_teacher not like", value, "GUIDANCE_TEACHER");
            return (Criteria) this;
        }

        public Criteria andGuidanceTeacherIn(List<String> values) {
            addCriterion("guidance_teacher in", values, "GUIDANCE_TEACHER");
            return (Criteria) this;
        }

        public Criteria andGuidanceTeacherNotIn(List<String> values) {
            addCriterion("guidance_teacher not in", values, "GUIDANCE_TEACHER");
            return (Criteria) this;
        }

        public Criteria andGuidanceTeacherBetween(String value1, String value2) {
            addCriterion("guidance_teacher between", value1, value2, "GUIDANCE_TEACHER");
            return (Criteria) this;
        }

        public Criteria andGuidanceTeacherNotBetween(String value1, String value2) {
            addCriterion("guidance_teacher not between", value1, value2, "GUIDANCE_TEACHER");
            return (Criteria) this;
        }

        public Criteria andHonorLevelIsNull() {
            addCriterion("honor_level is null");
            return (Criteria) this;
        }

        public Criteria andHonorLevelIsNotNull() {
            addCriterion("honor_level is not null");
            return (Criteria) this;
        }

        public Criteria andHonorLevelEqualTo(String value) {
            addCriterion("honor_level =", value, "HONOR_LEVEL");
            return (Criteria) this;
        }

        public Criteria andHonorLevelNotEqualTo(String value) {
            addCriterion("honor_level <>", value, "HONOR_LEVEL");
            return (Criteria) this;
        }

        public Criteria andHonorLevelGreaterThan(String value) {
            addCriterion("honor_level >", value, "HONOR_LEVEL");
            return (Criteria) this;
        }

        public Criteria andHonorLevelGreaterThanOrEqualTo(String value) {
            addCriterion("honor_level >=", value, "HONOR_LEVEL");
            return (Criteria) this;
        }

        public Criteria andHonorLevelLessThan(String value) {
            addCriterion("honor_level <", value, "HONOR_LEVEL");
            return (Criteria) this;
        }

        public Criteria andHonorLevelLessThanOrEqualTo(String value) {
            addCriterion("honor_level <=", value, "HONOR_LEVEL");
            return (Criteria) this;
        }

        public Criteria andHonorLevelLike(String value) {
            addCriterion("honor_level like", value, "HONOR_LEVEL");
            return (Criteria) this;
        }

        public Criteria andHonorLevelNotLike(String value) {
            addCriterion("honor_level not like", value, "HONOR_LEVEL");
            return (Criteria) this;
        }

        public Criteria andHonorLevelIn(List<String> values) {
            addCriterion("honor_level in", values, "HONOR_LEVEL");
            return (Criteria) this;
        }

        public Criteria andHonorLevelNotIn(List<String> values) {
            addCriterion("honor_level not in", values, "HONOR_LEVEL");
            return (Criteria) this;
        }

        public Criteria andHonorLevelBetween(String value1, String value2) {
            addCriterion("honor_level between", value1, value2, "HONOR_LEVEL");
            return (Criteria) this;
        }

        public Criteria andHonorLevelNotBetween(String value1, String value2) {
            addCriterion("honor_level not between", value1, value2, "HONOR_LEVEL");
            return (Criteria) this;
        }

        public Criteria andMessageIsNull() {
            addCriterion("MESSAGE is null");
            return (Criteria) this;
        }

        public Criteria andMessageIsNotNull() {
            addCriterion("MESSAGE is not null");
            return (Criteria) this;
        }

        public Criteria andMessageEqualTo(String value) {
            addCriterion("MESSAGE =", value, "MESSAGE");
            return (Criteria) this;
        }

        public Criteria andMessageNotEqualTo(String value) {
            addCriterion("MESSAGE <>", value, "MESSAGE");
            return (Criteria) this;
        }

        public Criteria andMessageGreaterThan(String value) {
            addCriterion("MESSAGE >", value, "MESSAGE");
            return (Criteria) this;
        }

        public Criteria andMessageGreaterThanOrEqualTo(String value) {
            addCriterion("MESSAGE >=", value, "MESSAGE");
            return (Criteria) this;
        }

        public Criteria andMessageLessThan(String value) {
            addCriterion("MESSAGE <", value, "MESSAGE");
            return (Criteria) this;
        }

        public Criteria andMessageLessThanOrEqualTo(String value) {
            addCriterion("MESSAGE <=", value, "MESSAGE");
            return (Criteria) this;
        }

        public Criteria andMessageLike(String value) {
            addCriterion("MESSAGE like", value, "MESSAGE");
            return (Criteria) this;
        }

        public Criteria andMessageNotLike(String value) {
            addCriterion("MESSAGE not like", value, "MESSAGE");
            return (Criteria) this;
        }

        public Criteria andMessageIn(List<String> values) {
            addCriterion("MESSAGE in", values, "MESSAGE");
            return (Criteria) this;
        }

        public Criteria andMessageNotIn(List<String> values) {
            addCriterion("MESSAGE not in", values, "MESSAGE");
            return (Criteria) this;
        }

        public Criteria andMessageBetween(String value1, String value2) {
            addCriterion("MESSAGE between", value1, value2, "MESSAGE");
            return (Criteria) this;
        }

        public Criteria andMessageNotBetween(String value1, String value2) {
            addCriterion("MESSAGE not between", value1, value2, "MESSAGE");
            return (Criteria) this;
        }

        public Criteria andPassIsNull() {
            addCriterion("pass is null");
            return (Criteria) this;
        }

        public Criteria andPassIsNotNull() {
            addCriterion("pass is not null");
            return (Criteria) this;
        }

        public Criteria andPassEqualTo(Byte value) {
            addCriterion("pass =", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassNotEqualTo(Byte value) {
            addCriterion("pass <>", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassGreaterThan(Byte value) {
            addCriterion("pass >", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassGreaterThanOrEqualTo(Byte value) {
            addCriterion("pass >=", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassLessThan(Byte value) {
            addCriterion("pass <", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassLessThanOrEqualTo(Byte value) {
            addCriterion("pass <=", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassIn(List<Byte> values) {
            addCriterion("pass in", values, "pass");
            return (Criteria) this;
        }

        public Criteria andPassNotIn(List<Byte> values) {
            addCriterion("pass not in", values, "pass");
            return (Criteria) this;
        }

        public Criteria andPassBetween(Byte value1, Byte value2) {
            addCriterion("pass between", value1, value2, "pass");
            return (Criteria) this;
        }

        public Criteria andPassNotBetween(Byte value1, Byte value2) {
            addCriterion("pass not between", value1, value2, "pass");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table competition_honor
     *
     * @mbg.generated do_not_delete_during_merge Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table competition_honor
     *
     * @mbg.generated Sat Nov 02 20:28:40 GMT+08:00 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}