package com.ayang818.honor.datacollection.model;

import java.util.Date;

public class Graduation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduation.id
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduation.student_name
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduation.school_number
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    private Integer schoolNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduation.teacher_id
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    private Integer teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduation.teacher_name
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    private String teacherName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduation.whereabouts
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    private String whereabouts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduation.gmt_create
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduation.gmt_modified
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduation.goneType
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    private String gonetype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduation.id
     *
     * @return the value of graduation.id
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduation.id
     *
     * @param id the value for graduation.id
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduation.student_name
     *
     * @return the value of graduation.student_name
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduation.student_name
     *
     * @param studentName the value for graduation.student_name
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduation.school_number
     *
     * @return the value of graduation.school_number
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    public Integer getSchoolNumber() {
        return schoolNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduation.school_number
     *
     * @param schoolNumber the value for graduation.school_number
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    public void setSchoolNumber(Integer schoolNumber) {
        this.schoolNumber = schoolNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduation.teacher_id
     *
     * @return the value of graduation.teacher_id
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduation.teacher_id
     *
     * @param teacherId the value for graduation.teacher_id
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduation.teacher_name
     *
     * @return the value of graduation.teacher_name
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduation.teacher_name
     *
     * @param teacherName the value for graduation.teacher_name
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduation.whereabouts
     *
     * @return the value of graduation.whereabouts
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    public String getWhereabouts() {
        return whereabouts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduation.whereabouts
     *
     * @param whereabouts the value for graduation.whereabouts
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    public void setWhereabouts(String whereabouts) {
        this.whereabouts = whereabouts == null ? null : whereabouts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduation.gmt_create
     *
     * @return the value of graduation.gmt_create
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduation.gmt_create
     *
     * @param gmtCreate the value for graduation.gmt_create
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduation.gmt_modified
     *
     * @return the value of graduation.gmt_modified
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduation.gmt_modified
     *
     * @param gmtModified the value for graduation.gmt_modified
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduation.goneType
     *
     * @return the value of graduation.goneType
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    public String getGonetype() {
        return gonetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduation.goneType
     *
     * @param gonetype the value for graduation.goneType
     *
     * @mbg.generated Sun Oct 27 18:28:02 GMT+08:00 2019
     */
    public void setGonetype(String gonetype) {
        this.gonetype = gonetype == null ? null : gonetype.trim();
    }
}