package com.ayang818.honor.datacollection.mapper;

import com.ayang818.honor.datacollection.model.Category;
import com.ayang818.honor.datacollection.model.CategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories_dict
     *
     * @mbg.generated Sun Nov 03 15:07:40 GMT+08:00 2019
     */
    long countByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories_dict
     *
     * @mbg.generated Sun Nov 03 15:07:40 GMT+08:00 2019
     */
    int deleteByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories_dict
     *
     * @mbg.generated Sun Nov 03 15:07:40 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories_dict
     *
     * @mbg.generated Sun Nov 03 15:07:40 GMT+08:00 2019
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories_dict
     *
     * @mbg.generated Sun Nov 03 15:07:40 GMT+08:00 2019
     */
    int insertSelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories_dict
     *
     * @mbg.generated Sun Nov 03 15:07:40 GMT+08:00 2019
     */
    List<Category> selectByExampleWithRowbounds(CategoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories_dict
     *
     * @mbg.generated Sun Nov 03 15:07:40 GMT+08:00 2019
     */
    List<Category> selectByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories_dict
     *
     * @mbg.generated Sun Nov 03 15:07:40 GMT+08:00 2019
     */
    Category selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories_dict
     *
     * @mbg.generated Sun Nov 03 15:07:40 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Category record, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories_dict
     *
     * @mbg.generated Sun Nov 03 15:07:40 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Category record, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories_dict
     *
     * @mbg.generated Sun Nov 03 15:07:40 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories_dict
     *
     * @mbg.generated Sun Nov 03 15:07:40 GMT+08:00 2019
     */
    int updateByPrimaryKey(Category record);
}