package com.ayang818.honor.datacollection.mapper;

import com.ayang818.honor.datacollection.model.CompetionHonor;
import com.ayang818.honor.datacollection.model.CompetionHonorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CompetionHonorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition_honor
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    long countByExample(CompetionHonorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition_honor
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    int deleteByExample(CompetionHonorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition_honor
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition_honor
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    int insert(CompetionHonor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition_honor
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    int insertSelective(CompetionHonor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition_honor
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    List<CompetionHonor> selectByExampleWithRowbounds(CompetionHonorExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition_honor
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    List<CompetionHonor> selectByExample(CompetionHonorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition_honor
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    CompetionHonor selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition_honor
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") CompetionHonor record, @Param("example") CompetionHonorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition_honor
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    int updateByExample(@Param("record") CompetionHonor record, @Param("example") CompetionHonorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition_honor
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(CompetionHonor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition_honor
     *
     * @mbg.generated Fri Oct 25 14:31:57 GMT+08:00 2019
     */
    int updateByPrimaryKey(CompetionHonor record);
}