package com.ayang818.honor.datacollection.mapper;

import com.ayang818.honor.datacollection.model.Graduation;
import com.ayang818.honor.datacollection.model.GraduationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GraduationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation
     *
     * @mbg.generated Mon Oct 28 23:48:18 CST 2019
     */
    long countByExample(GraduationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation
     *
     * @mbg.generated Mon Oct 28 23:48:18 CST 2019
     */
    int deleteByExample(GraduationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation
     *
     * @mbg.generated Mon Oct 28 23:48:18 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation
     *
     * @mbg.generated Mon Oct 28 23:48:18 CST 2019
     */
    int insert(Graduation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation
     *
     * @mbg.generated Mon Oct 28 23:48:18 CST 2019
     */
    int insertSelective(Graduation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation
     *
     * @mbg.generated Mon Oct 28 23:48:18 CST 2019
     */
    List<Graduation> selectByExampleWithRowbounds(GraduationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation
     *
     * @mbg.generated Mon Oct 28 23:48:18 CST 2019
     */
    List<Graduation> selectByExample(GraduationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation
     *
     * @mbg.generated Mon Oct 28 23:48:18 CST 2019
     */
    Graduation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation
     *
     * @mbg.generated Mon Oct 28 23:48:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") Graduation record, @Param("example") GraduationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation
     *
     * @mbg.generated Mon Oct 28 23:48:18 CST 2019
     */
    int updateByExample(@Param("record") Graduation record, @Param("example") GraduationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation
     *
     * @mbg.generated Mon Oct 28 23:48:18 CST 2019
     */
    int updateByPrimaryKeySelective(Graduation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation
     *
     * @mbg.generated Mon Oct 28 23:48:18 CST 2019
     */
    int updateByPrimaryKey(Graduation record);
}