package com.ayang818.honor.datacollection.mapper;

import com.ayang818.honor.datacollection.model.TotalHonor;
import com.ayang818.honor.datacollection.model.TotalHonorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TotalHonorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_honor
     *
     * @mbg.generated Sat Oct 26 21:23:14 GMT+08:00 2019
     */
    long countByExample(TotalHonorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_honor
     *
     * @mbg.generated Sat Oct 26 21:23:14 GMT+08:00 2019
     */
    int deleteByExample(TotalHonorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_honor
     *
     * @mbg.generated Sat Oct 26 21:23:14 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_honor
     *
     * @mbg.generated Sat Oct 26 21:23:14 GMT+08:00 2019
     */
    int insert(TotalHonor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_honor
     *
     * @mbg.generated Sat Oct 26 21:23:14 GMT+08:00 2019
     */
    int insertSelective(TotalHonor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_honor
     *
     * @mbg.generated Sat Oct 26 21:23:14 GMT+08:00 2019
     */
    List<TotalHonor> selectByExampleWithRowbounds(TotalHonorExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_honor
     *
     * @mbg.generated Sat Oct 26 21:23:14 GMT+08:00 2019
     */
    List<TotalHonor> selectByExample(TotalHonorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_honor
     *
     * @mbg.generated Sat Oct 26 21:23:14 GMT+08:00 2019
     */
    TotalHonor selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_honor
     *
     * @mbg.generated Sat Oct 26 21:23:14 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") TotalHonor record, @Param("example") TotalHonorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_honor
     *
     * @mbg.generated Sat Oct 26 21:23:14 GMT+08:00 2019
     */
    int updateByExample(@Param("record") TotalHonor record, @Param("example") TotalHonorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_honor
     *
     * @mbg.generated Sat Oct 26 21:23:14 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(TotalHonor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_honor
     *
     * @mbg.generated Sat Oct 26 21:23:14 GMT+08:00 2019
     */
    int updateByPrimaryKey(TotalHonor record);
}